version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: items_db
    environment:
      MYSQL_DATABASE: itemsapp
      MYSQL_USER: itemsadmin
      MYSQL_PASSWORD: supersecret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build: .
    container_name: items_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/itemsapp
      SPRING_DATASOURCE_USERNAME: itemsadmin
      SPRING_DATASOURCE_PASSWORD: supersecret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always

volumes:
  db_data: